export default {
  // Login page
  login_page_title: 'Welcome back!',
  login_page_sub_title: 'Good to see you back! Quick, login to see what new jobs we have to offer.',
  login: 'Login',
  no_account: 'Not an account yet? Register',
  email_address: 'email address',
  password: 'Password',
  forgot_password: 'Forgot password?',
  login_button: 'Yes, log me in',
  enter_password: 'Enter your password',
  enter_email: 'Enter your email',
  register: 'Register',
  log_in_to_your_account: 'Log in to your account',
  // Register page
  register_page_title: 'Let\'s create an account',
  register_page_sub_title: 'You\'re just a few keystrokes away from finding your dream job.',
  already_an_account: 'Got an account? Login',
  register_button: 'Yes, create an account',
  generate_password: 'Generate a password here',
  // account
  account: 'Account',
  reset_password: 'Reset password',
  log_out: 'Log out',
  personal_details: 'Personal details',
  preferences: 'Preferences',
  work_experience: 'Work experience',
  educations: 'Educations',
  contact_information: 'Contact information',
  validation_errors: 'Your :attribute contains errors',
  phone_number: 'phone number',
  postal_code: 'postal code',
  house_number: 'house number',
  house_number_add_on: 'house number add on',
  street: 'street',
  city: 'city',
  name: 'name',
  surname: 'surname',
  add_on: 'Add on',
  placeholder_surname: 'Enter your surname',
  placeholder_name: 'Enter your name',
  placeholder_city: 'Enter your city',
  placeholder_street: 'Enter your street',
  placeholder_phone_number: 'Enter your phone number',
  placeholder_email: 'Enter your email address',
  address: 'Address',
  account_sub_title: 'We stored your account details here.',
  account_progress: 'Account progress',
  account_progress_sub_title: 'Complete it for even better job oppurtunities.',
  // Language
  dutch: 'Nederlands',
  english: 'English',
  // validation messages
  required: ':attribute is required.',
  invalid: ':attribute is invalid.',
  min_length: 'A minimal of :attribute characters is mandatory.',
  max_length: 'Cannot contain more than :attribute characters.'
}
