export default {
  login_page_title: 'Welkom terug!',
  login_page_sub_title: 'Goed dat je er weer bent! Log snel in om het nieuwste banenaanbod te bekijken.',
  login: 'Inloggen',
  no_account: 'Geen account? Registreer je',
  email_address: 'e-mailadres',
  password: 'Wachtwoord',
  forgot_password: 'Wachtwoord vergeten?',
  login_button: 'Snel inloggen',
  enter_password: 'Voer je wachtwoord in',
  enter_email: 'Voer je email in',
  register: 'Registreren',
  log_in_to_your_account: 'Inloggen op je account',
  // account
  account: 'Account',
  reset_password: 'Wijzig wachtwoord',
  log_out: 'Uitloggen',
  personal_details: 'Gegevens',
  preferences: 'Voorkeuren',
  work_experience: 'Werkervaring',
  educations: 'Opleidingen',
  contact_information: 'Contactinformatie',
  validation_errors: 'Je :attribute klopt niet',
  phone_number: 'telefoonnummer',
  postal_code: 'postcode',
  house_number: 'huisnummer',
  house_number_add_on: 'toevoeging',
  street: 'straat',
  city: 'woonplaats',
  name: 'naam',
  surname: 'achternaam',
  add_on: 'toevoeging',
  placeholder_surname: 'Vul je achternaam in',
  placeholder_name: 'Voer je naam in',
  placeholder_city: 'Voer je woonplaats in',
  placeholder_street: 'Voer je straat in',
  placeholder_phone_number: 'Voer je telefoonnummer in',
  placeholder_email: 'Voer je e-mailadres in',
  address: 'Adres',
  account_sub_title: 'We hebben je gegevens hier opgeslagen.',
  // Language
  dutch: 'Nederlands',
  english: 'English',
  // validation messages
  required: ':attribute is verplicht.',
  invalid: ':attribute is niet correct.',
  min_length: 'Minimaal :attribute karakters zijn verplicht.',
  max_length: 'Meer dan :attribute karaters is niet toegestaan.'
}
